title: anki-jekyll
email: m@pedroivanlopez.com
description: >- # this means to ignore newlines until "baseurl:"
  anki-jekyll

# Github Pages
url: //pedroivanlopez.com/anki-jekyll
baseurl: /anki-jekyll

twitter_username: lopezpdvn
github_username:  lopezpdvn

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - note-styles/
  - scripts/
  - "tmp.*"
  - notes/
